name: Run mqquant Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/v2/src

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python -m mqre_v2.cli.run_latest_pipeline
